#!/bin/bash
echo "Desinstalando..."
rm /bin/MTVPS
rm /bin/Ub
rm -r /etc/usuarios /etc/tempo
rm /bin/Uc
rm /bin/Ur
rm /bin/Mt
rm /bin/Dt
rm /bin/limit
rm /etc/firewall-block
rm /etc/ResetFirewall
rm /etc/add-host
rm /etc/install-addhost
rm /etc/Ds
clear
echo "complete"
