#!/bin/bash
echo -e "\033[40;1;37m MTVPS Detalhes \033[0m
\033[1;33mSempre execute com o usuário root
você pode virar root com \033[1;31msu \033[1;33mou \033[1;31msudo su"

echo -e "\033[1;32m
Ferramenta Limit:\033[1;36m

Essa ferramenta monitora o número de conexões de usuários que teve seu limite aplicado
Use essa ferramenta pelo MTVPS (recomendado)
Tbm pode a usar com apenas um comando \033[1;33mlimit usuario limite\033[0m
\033[1;36mAo exceder o limite as conexoes excedentes serao desconectados !!
 
\033[1;32mUc:

\033[1;36mObjetivo criar usuarios de forma rapida e aplicando uma validade em dias
Para executar comando: Uc
Ou execute pelo MTVPS

\033[1;32mUb:

\033[1;36mObjetivo: Escolher entre deletar usuarios Forçar o deletamento e tambem desconectar todos de um usuario.
Para executar: Ub
Ou execute pelo MTVPS.

\033[1;32mUr:

\033[1;36mFerramenta para redefinir o limite de logins de um usuario ou redefinir a data de expiraçao de um usuario.
Para executar: Ur
Ou execute pelo MTVPS

\033[1;32mInstall-addhosts & add-hosts:

\033[1;36mA ferramenta Install-addhosts so deve ser usada uma vez ela prepara diretorios para a ferramenta add-hosts

Ferramenta add-hosts ela adiciona novos dominios (hosts payloads) em qualquer tipo de squid.conf

Execute pelo MTVPS

\033[1;32mFirewall-block & firewall-reset:

\033[1;36mFerramenta firewall-block faz o bloqueio torrent e protocolo icmp

Firewall-reset desfaz todas as regras iptables desabilitando qualquer bloqueio no firewall

ATENÇAO ESSAS DUAS FERRAMENTAS PODEM CAUSAR PROBLEMAS EXECUTE POR SUA CONTA
MUITAS EMPRESAS USAM O IPTABLES EM SUAS MAQUINAS VIRTUAIS E ESSE NÃO PODE SER ALTERADO

Execute pelo MTVPS

\033[1;32mMt:

\033[1;36mImportante ferramenta que lhe mostra quantas conexões em cada usuário.

OUTROS:
PARA RETIRAR O LIMITE DE CONEXOES DE UM USUARIO OU DE TODOS APAGUE

rm /etc/usuarios/usuario.sh
rm /etc/tempo/usuario.sh

Ou retire o limite de todos

rm -r /etc/tempo /etc/usuarios

\033[40;1;37m  FEITO POR TOMADA M. \033[0m"
