#!/bin/bash
clear
read -p "Qual o nome do usuário a redefinir: " namer
 if cat /etc/passwd |grep $namer: > /dev/null
 then
 echo " "
 else
 clear
 echo "Usuário $namer não existe"
 exit
 fi
clear

	echo -e "\033[1;32mLimite de logins para $namer:\033[0;37m"; read -p " " limit
  limit $namer $liml
exit 0
fi

