#!/bin/bash
clear
echo -e "     \033[40;1;37m CONFIGURAÇÃO MTVPS  \033[0m"
echo -e "\033[1;31mNo Span, no DDoS, no Torrent, no fraud. Qualquer desrespeito ou violação dos requisitos impostos pela empresa MegaTúnel, estará sujeito a suspensão definitiva do serviço sem aviso prévio e SEM REEMBOLSO!!!\033[0m"
echo -e "\033[1;37mMenu de opçoẽs:    \033[1;37mPara sair (de qualquer lugar) Ctrl + C\033[1;33m

Li \033[1;30m(limite de conexões simultâneas)\033[1;33m

Uc \033[1;30m(Criar usuários)\033[1;33m

Ur \033[1;30m(Opções para mudanças no usuário. Acesse ajuda)\033[1;33m

Ub \033[1;30m(Deletar, Desconectar, Opções. Acesse ajuda e saiba mais)\033[1;33m

Ah \033[1;30m(Adicionar novos Hosts de operadoras e terceiros aceitos pelo squid, caso tenha problemas de conexão com alguma Payload.)\033[1;33m

Mt \033[1;30m(Monitore as conexões por usuários. Acesse ajuda)\033[0m\033[1;33m

Bk \033[1;30m(Backup dos usuários incluindo limite de login simultâneos)\033[1;33m

Ru \033[1;30m(Restaurar backup de usuários, caso tenha feito)\033[1;33m

Du \033[1;30m(Exibir informações sobre os usuários já criados, como data, limite, usuário e senha)\033[1;33m

Bn \033[1;30m(Adicionar Banner paa ser visualizado por usuários no HTTP INJECTOR por exemplo)\033[1;33m

Sp \033[1;30m(Teste de conexão [velocidade de banda])\033[1;33m"
exit 0
fi