#!/bin/bash

if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Você não é root"
	echo "Seu usuário está no grupo sudo"
	echo -e "Para tornar-se root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Você não está como usuário root, nem com seus direitos (sudo)\nPara tornar-se root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi

if [ -d /etc/tomada ]
then
echo ""
else
mkdir /etc/tomada
fi

if [ -d /etc/tomada/senha ]
then
echo ""
else
mkdir /etc/tomada/senha
fi

if [ -d /etc/tomada/limite ]
then
echo ""
else
mkdir /etc/tomada/limite
fi

clear
echo -e "     \033[40;1;37m CONF. MTVPS BY TOMADA M. - ADAPTÇAO DO: VpsPacket  By Luiz Henrique  \033[0m"
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair Ctrl + C\033[1;33m
[1] Li \033[1;30m(limite de conexões simultâneas)\033[1;33m
[2] Uc \033[1;30m(Criar usuários)\033[1;33m
[3] Ur \033[1;30m(Opções para mudanças no usuário)\033[1;33m
[4] Ub \033[1;30m(Deletar, Desconectar, Opções)\033[1;33m
[5] Firewall-block \033[1;30m(Regras iptables block torrent, icmp [RISCOS])\033[1;33m
[6] ResetFirewall \033[1;30m(Retira todas as regras iptables [RISCOS])\033[1;33m
[7] Istall-addhosts \033[1;30m(Faz a preparação para add-host)\033[1;33m
[8] Ah \033[1;30m(Adicionar hosts aceitos pelo squid )\033[1;33m
[9] Mt \033[1;30m(IMPORTANTE monitorar conexões por usuários)\033[0m\033[1;33m
[10] Bk \033[1;30m(Backup dos usuários para reinstalação futura)\033[1;33m
[11] Ru \033[1;30m(Restaurar usuários feito backup)\033[1;33m
[12] Du \033[1;30m(Mostra informações sobre os usuários.)\033[1;33m
[13] Bn \033[1;30m(Banner mensagem do servodor no ssh)\033[1;33m
[14] Sp \033[1;30m(Teste de conexão [velocidade de banda])\033[1;33m
[15] Sd \033[1;30m(Detalhes sobre o Sistema [Created BadGuy])\033[1;33m
[16] Dt \033[1;30m(Detalhes sobre o MT VPS CONF.)\033[1;33m
[17] Ds \033[1;30m(Remover o MTVPS)\033[0m"
read -p ": " opcao

case $opcao in
 1)
  read -p "Usuário: " user
  read -p "Limite de conexões: " limit
  limit $user $limit;;
 2)
  Uc;;
 3)
  Ur;;
 4)
  Ub;;
 5)
  firewall-block;;
 6)
  ResetFirewall;;
 7)
  install-addhost;;
 8)
  Ah;;
 9)
  Mt;;
 10)
  Bk;; 
 11)
  read -p "Em qual diretório está o arquivo de Backup: " arq 
  Ru $arq;;
 12)
  Du;;
 13)
  Bn;;
 14)
  Sp;;
 15)
  Sd;;
 16)
  Dt;;
 17)
  Ds;;
 *)
  id > /dev/null 2> /dev/null
esac
