#!/bin/bash

clear
echo -e "\033[41;1;37mOpções:\033[0m
\033[1;36m1) Deletar usuário
2) Mudar a senha do usuário
3) Deletar e desconectar todos do usuário
4) Desconectar todos do usuário\033[0m"
read -p "opção: " option

 if [ $option -eq 1 ]; then
 read -p "Qual o nome do usuário: " name
 userdel --force $name > /dev/null 2>/dev/null
 echo "Usuário $name foi deletado"
 exit
 fi

if [ $option -eq 2 ]; then
 read -p "Qual o nome do usuário: " name
 read -p "Qual a nova senha: " pass
 (echo $pass; echo $pass)|passwd $name 2>/dev/null
 echo "A nova senha do usuário $name é: $pass"
 echo "$pass" > /etc/tomada/senha/$name
 exit
 fi

 if [ $option -eq 3 ]; then
 read -p "Qual o nome do usuário: " name
 userdel --force $name > /dev/null 2>/dev/null
 kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}` 2> /dev/null
 echo "Usuário $name foi deletado e parado"
 exit
 fi

 if [ $option -eq 4 ]; then
 read -p "Qual o nome do usuário: " name
 kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}` 2> /dev/null
 echo "Usuário $name foi parado"
 exit
 fi

echo "Essa opçao não existe"
